# OpenVPN image provided by SeeTheProgress
FROM seetheprogress/ubuntu:14.10
MAINTAINER Michael Grosser <docker@seetheprogress.net>

# Install OpenVPN and related packages
RUN apt-get -y install openvpn easy-rsa
