# Base image provided by SeeTheProgress
FROM seetheprogress/ubuntu:14.10
MAINTAINER Michael Grosser <docker@seetheprogress.net>

# Add bash welcome message
RUN echo 'echo ">Engineering your progress"' > ~/.bashrc
